# POST http://localhost:3000/login
# Content-Type: application/json

# {
#     "username": "ankush",
#     "password": "12345"
# }


# POST http://localhost:3000/user
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFua3VzaCIsImlhdCI6MTc1NDgzNDQ2OCwiZXhwIjoxNzU0ODM4MDY4fQ.6L698AqUJgYUqpU0pgR4DzHKlvpUvmssG_RqA4UXvjA

# {
#     "name": "Ankush",
#     "email": "ankush@example.com"
# }


POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "iPad",
  "price": 1500,
  "stock": 8

}



